# Generated by Django 4.1.7 on 2023-05-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_image_event_iframe_code_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='iframe_code',
            field=models.TextField(null=True, verbose_name='Код для вставки видео'),
        ),
    ]
