# Generated by Django 4.1.7 on 2023-05-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_iframe_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='iframe_code',
            field=models.TextField(blank=True, default='', verbose_name='Код для вставки видео'),
            preserve_default=False,
        ),
    ]
