# Generated by Django 4.1.6 on 2023-02-05 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('nationality', models.TextField()),
                ('activity', models.TextField()),
                ('family_status', models.TextField()),
                ('children', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='meeting/profile/', verbose_name='Фото профиля')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('-pub_date',),
            },
        ),
    ]
