# Generated by Django 4.1.7 on 2023-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
