# Generated by Django 4.1.7 on 2023-05-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.CharField(max_length=200, verbose_name='Деятельность'),
        ),
    ]
