# Generated by Django 4.1.7 on 2023-04-06 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='administrations/', verbose_name='Фото')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdministrationMemeber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Администратор группы',
                'verbose_name_plural': 'Администраторы группы',
                'ordering': ('-fio',),
            },
        ),
    ]
