# Generated by Django 4.1.7 on 2023-04-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratormember',
            options={'ordering': ('-fio',), 'verbose_name': 'Член администрации', 'verbose_name_plural': 'Члены администрации'},
        ),
    ]
