# Generated by Django 4.1.7 on 2023-04-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Изображение главной страницы'},
        ),
    ]
