# Generated by Django 4.1.7 on 2023-04-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_administratormember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratormember',
            options={'ordering': ('-fio',), 'verbose_name': 'Администратор', 'verbose_name_plural': 'Члены администрации'},
        ),
        migrations.AlterField(
            model_name='administratormember',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='administratormember',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
