# Generated by Django 4.1.7 on 2023-04-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_administratormember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administratormember',
            name='author',
        ),
    ]
