# Generated by Django 4.1.7 on 2023-04-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_administratormember_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratormember',
            options={'ordering': ('-fio',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники администрации'},
        ),
    ]
