# Generated by Django 4.1.7 on 2023-04-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_banner_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created_at',
        ),
        migrations.AddField(
            model_name='banner',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
