# Generated by Django 4.1.7 on 2023-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_banner_options_remove_banner_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Изображение для главной страницы', 'verbose_name_plural': 'Изображения для главной страницы'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
