# Generated by Django 4.1.7 on 2023-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_administratormember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratormember',
            name='bio',
            field=models.TextField(default='-', verbose_name='Краткая биография'),
            preserve_default=False,
        ),
    ]
