# Generated by Django 4.1.7 on 2023-05-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratormember',
            name='image',
            field=models.ImageField(upload_to='administrations/', verbose_name='Изображение'),
        ),
    ]
