# Generated by Django 4.1.7 on 2023-04-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etnoshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
