# Generated by Django 4.1.7 on 2023-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options_alter_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='iso_end',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='iso_start',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
