# Generated by Django 4.1.7 on 2023-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_iso_end_schedule_iso_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='iso_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='iso_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
