# Generated by Django 2.2.16 on 2022-04-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created",), "verbose_name_plural": "Статьи"},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="pub_date",
            new_name="created",
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата публикации"
            ),
        ),
    ]
